/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114701-g2d79ae3f8a-20240407"
#endif /* AVUTIL_FFVERSION_H */
